### ISSUE TITLE
FOR REVIEW - Make conda virtualenv for this script 

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/make-xls-model#15]
- [ ] Create an environment for running this script based on miniconda3 using conda manager
  Intent: to have a least-size movable python distribution that can run this script
  Delieverable: windows script to do this job of creating environment.
- [ ] Produce requirements.txt
  Intent: allow someone not using Anaconda to install necessary packages using pip
  Delieverable: windows script to do this job
- [ ] Educate about differences of building virtual envs with virtualenv and conda
  Intent: understand what is going on
- [ ] Advise on feasability of packaging this script to Win32 executable and making it small in size 
  (for example - the script relies on pandas library, which is big and may not fit well into single binary).

**Comment by epogrebnyak** [comment]
Tried pipreqs, hangs with following message:

```
D:\Programs\miniconda3>pipreqs D:\git\make-xls-model\src
Traceback (most recent call last):
  File "D:\Anaconda3\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda3\Scripts\pipreqs.exe\__main__.py", line 9, in <module>
  File "D:\Anaconda3\lib\site-packages\pipreqs\pipreqs.py", line 178, in main
    init(args)
  File "D:\Anaconda3\lib\site-packages\pipreqs\pipreqs.py", line 147, in init
    candidates = get_all_imports(args['<path>'])
  File "D:\Anaconda3\lib\site-packages\pipreqs\pipreqs.py", line 43, in get_all_imports
    for line in lines:
  File "D:\Anaconda3\lib\encodings\cp1251.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 6011: character maps to <unde
fined>
```

**Comment by epogrebnyak** [comment]
16:33 01.08.2015
http://stackoverflow.com/questions/19280894/py2exe-no-system-module-pywintypes
http://stackoverflow.com/questions/17891071/importerror-with-cx-freeze-and-pywin32-module-pythoncom-isnt-in-frozen-sys-p
